In [1]:
import pandas as pd
import numpy as np

from allensdk.experimental.nwb.tests.utilities.compare import compare, nested_compare, as_dataframe

In [2]:
left = {
    'a': {
        'b': 1
    },
    'c': np.array([1, 2, 3, 4, 5])
}
right = {
    'a': {
        'b': 2
    },
    'c': [1, 2, 3, 4, 5]
}

In [3]:
results = nested_compare(left, right)

In [6]:
results_dataframe = as_dataframe(results)
results_dataframe

,direct_diff,direct_equal,left_name,right_name,types_diff,types_equal
0,,True,initial,initial,"left type: <class 'dict'>, right type: <class ...",True
1,"5 elements in left, 5 in right",True,c,c,"left type: <class 'numpy.ndarray'>, right type...",False
2,5 vs 5,True,4,4,"left type: <class 'numpy.int64'>, right type: ...",False
3,4 vs 4,True,3,3,"left type: <class 'numpy.int64'>, right type: ...",False
4,3 vs 3,True,2,2,"left type: <class 'numpy.int64'>, right type: ...",False
5,2 vs 2,True,1,1,"left type: <class 'numpy.int64'>, right type: ...",False
6,1 vs 1,True,0,0,"left type: <class 'numpy.int64'>, right type: ...",False
7,,True,a,a,"left type: <class 'dict'>, right type: <class ...",True
8,1 vs 2,False,b,b,"left type: <class 'int'>, right type: <class '...",True

In [7]:
mismatch_dataframe = results_dataframe[~(results_dataframe['direct_equal'])]
mismatch_dataframe

,direct_diff,direct_equal,left_name,right_name,types_diff,types_equal
8,1 vs 2,False,b,b,"left type: <class 'int'>, right type: <class '...",True